"""Each integration test gets a fresh schema/user; existing demo data is never reset."""
import os
from pathlib import Path
import re
import secrets
import sys
from uuid import uuid4

import mysql.connector
import pytest

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "scripts"))
from sql_runner import install
from seed_demo import seed, DEMO_PASSWORD
from app import create_app


@pytest.fixture
def app():
    if not (ROOT / ".local/mysql/data/mysql").is_dir():
        pytest.skip("Isolated project MySQL has not been initialized")
    root = mysql.connector.connect(host="127.0.0.1", port=3307, user="root", password="", autocommit=True)
    token = uuid4().hex[:12]
    schema, db_user, password = f"healthcare_test_{token}", f"clinic_test_{token}", secrets.token_urlsafe(24)
    try:
        with root.cursor() as cursor:
            cursor.execute(f"CREATE DATABASE `{schema}` CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci")
        root.database = schema
        install(root)
        seed(root)
        with root.cursor() as cursor:
            cursor.execute(f"CREATE USER '{db_user}'@'127.0.0.1' IDENTIFIED BY %s", (password,))
            cursor.execute(f"GRANT SELECT, INSERT, UPDATE ON `{schema}`.* TO '{db_user}'@'127.0.0.1'")
        instance = create_app({"TESTING": True, "SECRET_KEY": secrets.token_urlsafe(32),
            "MYSQL_DATABASE": schema, "MYSQL_USER": db_user, "MYSQL_PASSWORD": password,
            "MYSQL_HOST": "127.0.0.1", "MYSQL_PORT": 3307, "WTF_CSRF_ENABLED": True})
        instance.test_root = root
        yield instance
    finally:
        # Cleanup targets only names generated by this fixture, never a user-provided schema.
        assert schema == f"healthcare_test_{token}" and db_user == f"clinic_test_{token}"
        with root.cursor() as cursor:
            cursor.execute(f"DROP DATABASE IF EXISTS `{schema}`")
            cursor.execute(f"DROP USER IF EXISTS '{db_user}'@'127.0.0.1'")
        root.close()


@pytest.fixture
def client(app):
    return app.test_client()


def post(client, path, data=None):
    html = client.get("/auth/login").get_data(as_text=True)
    match = re.search(r'name="csrf_token"[^>]*value="([^"]+)"', html)
    assert match, "CSRF token must be rendered"
    return client.post(path, data={**(data or {}), "csrf_token": match.group(1)})


def login(client, username):
    response = post(client, "/auth/login", {"username": username, "password": DEMO_PASSWORD})
    assert response.status_code == 302
    return response


def sql(app, statement, params=(), *, one=False):
    with app.test_root.cursor(dictionary=True) as cursor:
        cursor.execute(statement, params)
        if cursor.with_rows:
            return cursor.fetchone() if one else cursor.fetchall()
        return cursor.rowcount
